### ISSUE TITLE
PSR-14 is Accepted 🎉

### ISSUE THREAD

**Issue by szepeviktor** [Dhii/psr-14#3]
See https://www.php-fig.org/psr/

@XedinUnknown What is the next step?

**Comment by XedinUnknown** [comment]
Hi @szepeviktor! And thanks for submitting this.

Indeed, PSR-14 has been accepted a while ago. And it's nothing like it was before! Therefore, unfortunately this repo is deprecated. However, a compliant wrapper is being developed (by me). You can track progress at [`inpsyde/wp-events`][].

[`inpsyde/wp-events`]: https://github.com/inpsyde/wp-events

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@XedinUnknown Could you please tell me whether that repo is public?
